/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import com.robsonbruno.tcc_final.CelulasParaconsistentes.CCIR;
import com.robsonbruno.tcc_final.MetodosDePonderacao.BushyPath;
import com.robsonbruno.tcc_final.MetodosDePonderacao.CentrFrasesInters;
import com.robsonbruno.tcc_final.MetodosDePonderacao.FreqPalavras;
import com.robsonbruno.tcc_final.MetodosDePonderacao.SimAgregada;
import com.robsonbruno.tcc_final.MetodosDePonderacao.SimTituloInters;
import com.robsonbruno.tcc_final.PLN.ProcessarTexto;
import com.robsonbruno.tcc_final.PLN.Texto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Robson Bruno
 */
public class TelaJFrame extends javax.swing.JFrame {
    
    private String Titulo="";
    private String Texto="";
    private String Resumo="";
    private String Descricao = " ";
    private ProcessarTexto Analise = new ProcessarTexto();
    private Texto Sentencas = new Texto();
    private List<String> ResumoList = new ArrayList<>();
    /**
     * Creates new form TelaJFrame
     */
    public TelaJFrame() {
        initComponents();
        //setExtendedState(java.awt.Frame.ICONIFIED);
        
        float alignx = jSpinnerFTd.getAlignmentX();
        float aligny = jSpinnerFTd.getAlignmentY();
        jSpinnerLimiar.setVisible(false);
        jSpinnerLimiar.setAlignmentX(alignx);
        jSpinnerLimiar.setAlignmentY(aligny);
        
        alignx = jLabel5.getAlignmentX();
        aligny = jLabel5.getAlignmentY();
        jLabel7.setVisible(false);
        jLabel7.setAlignmentX(alignx);
        jLabel7.setAlignmentY(aligny);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTexto = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaResumo = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxMetodos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SpinnerNumberModel model = new SpinnerNumberModel(0.00, 0.00, 1.00, 0.01);
        jSpinnerFTd = new javax.swing.JSpinner(model);
        jLabel6 = new javax.swing.JLabel();
        SpinnerNumberModel model2 = new SpinnerNumberModel(0.00, 0.00, 1.00, 0.01);
        jSpinnerFTct = new javax.swing.JSpinner(model2);
        jCheckBoxContradicao = new javax.swing.JCheckBox();
        jButtonResumir = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        SpinnerNumberModel model3 = new SpinnerNumberModel(0.00, 0.00, 1.00, 0.01);
        jSpinnerLimiar = new javax.swing.JSpinner(model3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1600, 800));

        jTabbedPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jTextFieldTitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Título:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Texto:");

        jTextAreaTexto.setLineWrap(true);
        jTextAreaTexto.setWrapStyleWord(true);
        jTextAreaTexto.setColumns(20);
        jTextAreaTexto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextAreaTexto.setRows(5);
        jTextAreaTexto.setMargin(new java.awt.Insets(10, 5, 10, 5));
        jScrollPane1.setViewportView(jTextAreaTexto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Texto Original", jPanel1);

        jTextAreaResumo.setEditable(false);
        jTextAreaResumo.setLineWrap(true);
        jTextAreaResumo.setWrapStyleWord(true);
        jTextAreaResumo.setColumns(20);
        jTextAreaResumo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextAreaResumo.setRows(5);
        jTextAreaResumo.setMargin(new java.awt.Insets(10, 5, 10, 5));
        jScrollPane2.setViewportView(jTextAreaResumo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Resumo", jPanel2);

        jTextAreaDescricao.setEditable(false);
        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setLineWrap(true);
        jTextAreaDescricao.setWrapStyleWord(true);
        jTextAreaDescricao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextAreaDescricao.setRows(5);
        jTextAreaDescricao.setMargin(new java.awt.Insets(10, 5, 10, 5));
        jScrollPane3.setViewportView(jTextAreaDescricao);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Processamento", jPanel3);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Tipo de Ponderação");

        jComboBoxMetodos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBoxMetodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bushy Path", "Centra. Frases", "Freq. Palavras", "Sim. Agregada", "Sim. Título", "Todos" }));
        jComboBoxMetodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMetodosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Parâmetros:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Tolerância a Decisão");

        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(jSpinnerFTd);
        jSpinnerFTd.setEditor(editor);
        jSpinnerFTd.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Tolerância a Contradição");

        JSpinner.NumberEditor editor2 = new JSpinner.NumberEditor(jSpinnerFTct);
        jSpinnerFTct.setEditor(editor2);
        jSpinnerFTct.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        jCheckBoxContradicao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBoxContradicao.setSelected(true);
        jCheckBoxContradicao.setText("Rede Neural Ativada");
        jCheckBoxContradicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxContradicaoActionPerformed(evt);
            }
        });

        jButtonResumir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonResumir.setText("Resumir");
        jButtonResumir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResumirActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Limiar de seleção:");

        JSpinner.NumberEditor editor3 = new JSpinner.NumberEditor(jSpinnerLimiar);
        jSpinnerLimiar.setEditor(editor3);
        jSpinnerLimiar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxMetodos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jSpinnerFTd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(66, 66, 66))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jSpinnerFTct, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(68, 68, 68)))
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jSpinnerLimiar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBoxContradicao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonResumir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxContradicao)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerFTd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerFTct, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinnerLimiar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonResumir)
                .addGap(18, 18, 18)
                .addComponent(jButtonLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1218, 847));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jComboBoxMetodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMetodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMetodosActionPerformed

    private void jCheckBoxContradicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxContradicaoActionPerformed
        // TODO add your handling code here:
        boolean Contradicao = jCheckBoxContradicao.isSelected();
        jSpinnerFTct.setVisible(Contradicao);
        jSpinnerFTd.setVisible(Contradicao);
        jLabel5.setVisible(Contradicao);
        jLabel6.setVisible(Contradicao);
        
        jLabel7.setVisible(!Contradicao);
        jSpinnerLimiar.setVisible(!Contradicao);
    }//GEN-LAST:event_jCheckBoxContradicaoActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        Titulo = "";
        Texto = "";
        ResumoList.clear();
        Resumo = "";
        Descricao = " ***RESULTADO DA ANÁLISE DAS SENTENÇAS DO TEXTO*** ";
        
        int tab = jTabbedPane.getSelectedIndex();
        switch(tab){
            case 0:
                jTextFieldTitulo.setText("");
                jTextAreaTexto.setText("");
                break;
            case 1:
                jTextAreaResumo.setText("");
                break;
            case 2:
                jTextAreaDescricao.setText("");
                break;
        }
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonResumirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResumirActionPerformed
        // TODO add your handling code here:
         if(jTabbedPane.getSelectedIndex()!=0)
            jButtonLimpar.doClick();
         else{
             jTabbedPane.setSelectedIndex(1);
             jButtonLimpar.doClick();
         }
         
         Titulo = jTextFieldTitulo.getText();
         Texto = jTextAreaTexto.getText();
        
        Analise = new ProcessarTexto();
        Analise.setTexto(Texto);
        Sentencas = new Texto();
        Sentencas.setFrases(Analise.getSentences());
        Sentencas.setTitulo(Titulo);
                
        String Metodo = jComboBoxMetodos.getSelectedItem().toString();
        
        switch(Metodo){
            case "Todos":
                todosOsMetodos();
                break;
            case "Bushy Path":
                bushyPath();
                break;
            case "Centra. Frases":
                centraFrases();
                break;
            case "Freq. Palavras":
                freqPalavras();
                break;
            case"Sim. Agregada":
                simAgregada();
                break;
            case "Sim. Título":
                SimTitulo();
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "ALERTA", "Método de ponderação não selecionado", ERROR);
                break;
        } 
        
        double FTct=0.0,FTd=0.0,Limiar=0.0;
        boolean Contradicao = jCheckBoxContradicao.isSelected();
        FTct = (double)jSpinnerFTct.getValue();
        FTd = (double) jSpinnerFTd.getValue();
        Limiar = (double) jSpinnerLimiar.getValue();
        
            
        CCIR Pensamento = new CCIR();
        Pensamento.setParamentros(FTct, FTd);
        if(Contradicao)
            ResumoList = Pensamento.avaliar(Sentencas);
        else
            ResumoList = Pensamento.avaliar(Sentencas, Limiar);
         
        Resumo  = String.join(".", ResumoList);
        jTextAreaResumo.setText(Sentencas.getTitulo()+"\n\n"+Resumo+".");
        
        int i=0;
        for(String Sentenca: Sentencas.getFrases()){
            Descricao = Descricao+"\n\n Frase: "+Sentenca+"\n Favorável: "+Sentencas.getResultadoPositivo().get(i)+"\n Contradição: "+Sentencas.getResultadoNegativo().get(i);
            i++;
        }
        i=0;
        jTextAreaDescricao.setText(Descricao);
    }//GEN-LAST:event_jButtonResumirActionPerformed
    
    private void bushyPath(){
        BushyPath Calcular = new BushyPath();
        Sentencas = Calcular.ponderar(Sentencas);
    }
    private void centraFrases(){
        CentrFrasesInters Calcular = new CentrFrasesInters();
        Sentencas = Calcular.ponderar(Sentencas);
    }
    private void freqPalavras(){
        FreqPalavras Calcular = new FreqPalavras();
        Sentencas = Calcular.ponderar(Sentencas);
    }
    private void simAgregada(){
        SimAgregada Calcular = new SimAgregada();
        Sentencas = Calcular.ponderar(Sentencas);
    }
    private void SimTitulo(){
        SimTituloInters Calcular = new SimTituloInters();
        Sentencas = Calcular.ponderar(Sentencas);
    }
    private void todosOsMetodos(){
        bushyPath();
        ArrayList<Double>[] B = (ArrayList<Double>[])new ArrayList[2];
        B[0] = new ArrayList<>(Sentencas.getResultadoPositivo());
        B[1] = new ArrayList<>(Sentencas.getResultadoNegativo());
        Sentencas.getResultadoNegativo().clear();
        Sentencas.getResultadoPositivo().clear();
        
        centraFrases();
        ArrayList<Double>[] CF = (ArrayList<Double>[])new ArrayList[2];
        CF[0] = new ArrayList<>(Sentencas.getResultadoPositivo());
        CF[1] = new ArrayList<>(Sentencas.getResultadoNegativo());
        Sentencas.getResultadoNegativo().clear();
        Sentencas.getResultadoPositivo().clear();
        
        freqPalavras();
        ArrayList<Double>[] F = (ArrayList<Double>[])new ArrayList[2];
        F[0] = new ArrayList<>(Sentencas.getResultadoPositivo());
        F[1] = new ArrayList<>(Sentencas.getResultadoNegativo());
        Sentencas.getResultadoNegativo().clear();
        Sentencas.getResultadoPositivo().clear();
        
        simAgregada();
        ArrayList<Double>[] SA = (ArrayList<Double>[])new ArrayList[2];
        SA[0] = new ArrayList<>(Sentencas.getResultadoPositivo());
        SA[1] = new ArrayList<>(Sentencas.getResultadoNegativo());
        Sentencas.getResultadoNegativo().clear();
        Sentencas.getResultadoPositivo().clear();
        
        SimTitulo();
        ArrayList<Double>[] ST = (ArrayList<Double>[])new ArrayList[2];
        ST[0] = new ArrayList<>(Sentencas.getResultadoPositivo());
        ST[1] = new ArrayList<>(Sentencas.getResultadoNegativo());
        Sentencas.getResultadoNegativo().clear();
        Sentencas.getResultadoPositivo().clear();
        
        ArrayList<Double> Positivos = new ArrayList<>();
        ArrayList<Double> Negativos = new ArrayList<>();
        int cont=0;
        
        for(String Sentenca: Sentencas.getFrases()){
            double b = B[0].get(cont);
            double cf = CF[0].get(cont);
            double f = F[0].get(cont);
            double sa = SA[0].get(cont);
            double st = ST[0].get(cont);
            Positivos.add((b+cf+f+sa+st)/5);

            b = B[1].get(cont);
            cf = CF[1].get(cont);
            f = F[1].get(cont);
            sa = SA[1].get(cont);
            st = ST[1].get(cont);
            Negativos.add((b+cf+f+sa+st)/5);
            
            cont++;
        }
        cont = 0;
        
        Sentencas.setResultadoNegativo(Negativos);
        Sentencas.setResultadoPositivo(Positivos);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonResumir;
    private javax.swing.JCheckBox jCheckBoxContradicao;
    private javax.swing.JComboBox<String> jComboBoxMetodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerFTct;
    private javax.swing.JSpinner jSpinnerFTd;
    private javax.swing.JSpinner jSpinnerLimiar;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextArea jTextAreaResumo;
    private javax.swing.JTextArea jTextAreaTexto;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables

    private void JOptionPane(String m) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
